language: node_js
node_js:
    - 14.4.0
branches:
    only:
        - master
before_script:
    - npm install -g @angular/cli
    - npm install -g bower
    - npm install -g firebase-tools
    - npm install -g forever
script:
    - cd api
    - npm install
    - node ./bin/www.js
    - cd ../client
    - npm install
    - npm run build
    - npx scully --sr
