language: node_js

node_js:
    - '10.14.0'

branches:
    only:
        - master

before_script:
    - npm install -g @angular/cli
    - npm install -g bower
    - npm install -g firebase-tools
    - npm install -g forever

script:
    - cd api
    - npm install
      # Start API as background proc via forever
    #  - forever start ./bin/www.js
    - node ./bin/www.js
    - cd ../client
    # Make client builds
    - npm install
    - npm run build
    - npx scully --sr
