language: node_js
node_js:
    - 14.4.0
branches:
    only:
        - master
services:
    - mongodb

before_script:
    - npm install -g @angular/cli
    - npm install -g bower
    - npm install -g firebase-tools
    - npm install -g forever
script:
    - chmod 777 db.sh
    - ./db.sh
    - cd api
    - npm install
    - forever start ./bin/www.js
    - echo "Pause for 1 min and output API log."
    - sleep 60
    - forever logs 0
    - cd ../client
    - npm install
    - npm run build
    - npx scully --sr
