language: node_js

node_js:

   - "10.14.0"

branches:

   only:

      - master


before_script:

   - npm install -g @angular/cli
   - npm install -g bower
   - npm install -g firebase-tools


script:
  
   - cd client
   - npm install
   - npm run build