name: build-tests
on: push
env:
  CI: true
jobs:
  test:
    name: "Export production build, run a11y tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install global packages
        run : npm install -g forever pa11y-ci pm2
      
      - name: Install API
        working-directory: ./api  
        run: npm install
      
      - name: Start API in background
        working-directory: ./api  
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          DB_URI: ${{ secrets.DB_URI }}
          NODE_ENV: staging
        run: |
          forever start ./bin/www.js prod
          echo "Pause for 1 min and output API log."
          sleep 60
          forever logs 0
    
      - name: Build and export static build of client
        working-directory: ./client
        run: |
          cd ../client
          npm install
          npm run build
          npx scully --sr
  
      # Run a11y checks via config in ./pa11yci config, w/ all routes discovered by Scully build
      - name: Start client dist build server via pm2, run a11y tests
        working-directory: ./client
        run: |
          pm2 start `which http-server` ../bin/app -- -p 1864
          pa11y-ci